#ifndef REGISTERRESULTSTATUS_H
#define REGISTERRESULTSTATUS_H

enum class RegisterResultStatus
{
    NOT_REGISTER,
    FORM_VALID_SUCCESSFULL,
    SUCCESSFULL,
    FAILED,
    INCORRECT_LOGIN,
    INCORRECT_PASSWORD,
    PASSWORD_NOT_CONFIRM,
    LOGIN_EXISTED
};

#endif // REGISTERRESULTSTATUS_H
